# Recovery
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_NO_REAL_SDCARD := true
BOARD_RECOVERY_SWIPE := true
TARGET_RECOVERY_QCOM_RTC_FIX := true
BOARD_USES_QC_TIME_SERVICES := true
BOARD_NO_SECURE_DISCARD := true
BOARD_SUPPRESS_SECURE_ERASE := true
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_23x41.h\"
TARGET_RECOVERY_FSTAB := device/KDDI/KYF31/recovery.fstab
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
BOARD_HAS_LARGE_FILESYSTEM := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
RECOVERY_SDCARD_ON_DATA := true

# exFAT FS Support
TW_INCLUDE_FUSE_EXFAT := true
#NTFS Support
#TW_INCLUDE_FUSE_NTFS := true

# Crypto
#TW_INCLUDE_CRYPTO := true

#TWRP config:
DEVICE_RESOLUTION := 480x854
DEVICE_SCREEN_WIDTH := 480
DEVICE_SCREEN_HEIGHT := 854
TW_NO_SCREEN_BLANK := true
TW_MAX_BRIGHTNESS := 255
TW_EXTRA_LANGUAGES := true
TW_DEFAULT_LANGUAGE := zh_CN
TW_THEME := portrait_hdpi
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TW_INCLUDE_NTFS_3G := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_SUPERSU := true
#TW_NO_EXFAT_FUSE := true
TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone1/temp
TW_INTERNAL_STORAGE_PATH := "/data/media"
TW_INTERNAL_STORAGE_MOUNT_POINT := "data"
#TW_USE_TOOLBOX := true

# Logging
#TWRP_INCLUDE_LOGCAT := true
#TARGET_USES_LOGD := true
#TWRP_EVENT_LOGGING := true

# Treble
BOARD_NEEDS_VENDORIMAGE_SYMLINK := false
TARGET_COPY_OUT_VENDOR := vendor
